import { Quicksand, Palanquin } from "next/font/google";
import "./globals.css";
import {fetchData} from "@/lib/api";
import localFont from "next/font/local";
import clsx from "clsx";
import StoryblokProvider from "@/components/providers/StoryblokProvider";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import pkg from "react";
import Header from "@/components/sections/hards/Header";
import Footer from "@/components/sections/hards/Footer";

storyblokInit({
    accessToken: process.env.STORYBLOK_API_TOKEN,
    use: [apiPlugin],
});
const quicksand = Quicksand({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    display: "swap",
    variable: "--font-quicksand"
});
const palanquin = Palanquin({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    display: "swap",
    variable: "--font-palanquin"
});

const pl = localFont({
    src: '../fonts/Palatino_Linotype.woff2',
    weight: '400',
    style: 'normal',
    variable: "--font-palatino"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}) {
     const { data } = await fetchData("global", {
         version: "draft",
     })
    //console.log(data);
    return (
        <html lang="en">
        <StoryblokProvider>
        <body
            className={clsx(quicksand.variable, palanquin.variable, pl.variable, "h-dvh")}>
        <Header data={data.story?.content?.headerLinks} />
        {children}
        <Footer data={{
            text: data.story?.content?.footerText,
            links: data.story?.content?.footerLinks
        }} />
        </body>
        </StoryblokProvider>
        </html>
    );
}
